"""add_digests_and_digest_items

Revision ID: 1df2f2fdd226
Revises: c246201ec040
Create Date: 2026-06-07 15:44:16.985627+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df2f2fdd226'
down_revision: Union[str, None] = 'c246201ec040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('workspace_id', sa.String(), nullable=False),
                    sa.Column('digest_date', sa.String(
                        length=10), nullable=False),
                    sa.Column('summary', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=20),
                              nullable=False, server_default='pending'),
                    sa.Column('email_sent_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('update_count', sa.Integer(),
                              nullable=False, server_default=sa.text('0')),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_digests_digest_date'),
                    'digests', ['digest_date'], unique=False)
    op.create_index(op.f('ix_digests_workspace_id'),
                    'digests', ['workspace_id'], unique=False)
    op.create_table('digest_items',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('digest_id', sa.String(), nullable=False),
                    sa.Column('update_id', sa.String(), nullable=False),
                    sa.Column('author_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('summary_snapshot', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['digest_id'], ['digests.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['update_id'], ['updates.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_digest_items_digest_id'),
                    'digest_items', ['digest_id'], unique=False)
    op.add_column('profiles', sa.Column(
        'email', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('digest_enabled',
                  sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('workspaces', sa.Column(
        'digest_send_time', sa.String(length=5), nullable=False, server_default='09:00'))
    op.add_column('workspaces', sa.Column(
        'digest_timezone', sa.String(length=64), nullable=True))
    op.add_column('workspaces', sa.Column(
        'digest_days', sa.String(length=20), nullable=False, server_default='1,2,3,4,5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'digest_days')
    op.drop_column('workspaces', 'digest_timezone')
    op.drop_column('workspaces', 'digest_send_time')
    op.drop_column('workspaces', 'digest_enabled')
    op.drop_column('profiles', 'email')
    op.drop_index(op.f('ix_digest_items_digest_id'), table_name='digest_items')
    op.drop_table('digest_items')
    op.drop_index(op.f('ix_digests_workspace_id'), table_name='digests')
    op.drop_index(op.f('ix_digests_digest_date'), table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
