"""add_username_bio_tagline_profile_public_to_profiles

Revision ID: fb090fad7a42
Revises: 4783b311c920
Create Date: 2026-07-02 22:41:05.799335+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb090fad7a42'  # pragma: allowlist secret
down_revision: Union[str, None] = '4783b311c920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('digests', 'delivered_to_slack',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.add_column('profiles', sa.Column(
        'username', sa.String(length=30), nullable=True))
    op.add_column('profiles', sa.Column(
        'bio', sa.String(length=160), nullable=True))
    op.add_column('profiles', sa.Column(
        'tagline', sa.String(length=60), nullable=True))
    op.add_column('profiles', sa.Column('profile_public', sa.Boolean(),
                  nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_profiles_username'),
                    'profiles', ['username'], unique=True)
    op.alter_column('workspaces', 'slack_digest_enabled',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('workspaces', 'slack_updates_enabled',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'slack_updates_enabled',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.alter_column('workspaces', 'slack_digest_enabled',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_column('profiles', 'profile_public')
    op.drop_column('profiles', 'tagline')
    op.drop_column('profiles', 'bio')
    op.drop_column('profiles', 'username')
    op.alter_column('digests', 'delivered_to_slack',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    # ### end Alembic commands ###
