"""add_is_onboarded_to_profiles

Revision ID: 20afec183981
Revises: 23e374fb93ee
Create Date: 2026-04-10 21:30:25.088253+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20afec183981'  # pragma: allowlist secret
down_revision: Union[str, None] = '23e374fb93ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "is_onboarded",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_onboarded')
    # ### end Alembic commands ###
