"""add_audio_fields_to_updates

Revision ID: c24b81e8beea
Revises: 0c3ab14699e7
Create Date: 2026-05-26 19:16:46.760661+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24b81e8beea'
down_revision: Union[str, None] = '0c3ab14699e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('audio_key', sa.String(length=500), nullable=True))
    op.add_column('updates', sa.Column('audio_url', sa.String(length=500), nullable=True))
    op.add_column('updates', sa.Column('audio_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'audio_duration_seconds')
    op.drop_column('updates', 'audio_url')
    op.drop_column('updates', 'audio_key')
    # ### end Alembic commands ###
