"""add_slack_config_to_workspaces

Revision ID: dc04381d2f54
Revises: 5b57c7a35427
Create Date: 2026-06-29 21:54:19.806245+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc04381d2f54'  # pragma: allowlist secret
down_revision: Union[str, None] = '5b57c7a35427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column(
        'delivered_to_slack', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('digests', sa.Column('slack_delivered_at',
                  sa.DateTime(timezone=True), nullable=True))
    op.alter_column('digests', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('digests', 'update_count',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('profiles', 'is_onboarded',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('workspace_members', 'role',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=None,
                    existing_nullable=False)
    op.add_column('workspaces', sa.Column(
        'slack_webhook_url_encrypted', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('slack_digest_enabled',
                  sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('workspaces', sa.Column('slack_updates_enabled',
                  sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('workspaces', 'plan',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('workspaces', 'digest_enabled',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('workspaces', 'digest_send_time',
                    existing_type=sa.VARCHAR(length=5),
                    server_default=None,
                    existing_nullable=False)
    op.alter_column('workspaces', 'digest_days',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=None,
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'digest_days',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'1,2,3,4,5'::character varying"),
                    existing_nullable=False)
    op.alter_column('workspaces', 'digest_send_time',
                    existing_type=sa.VARCHAR(length=5),
                    server_default=sa.text("'09:00'::character varying"),
                    existing_nullable=False)
    op.alter_column('workspaces', 'digest_enabled',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.alter_column('workspaces', 'plan',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'free'::character varying"),
                    existing_nullable=False)
    op.drop_column('workspaces', 'slack_updates_enabled')
    op.drop_column('workspaces', 'slack_digest_enabled')
    op.drop_column('workspaces', 'slack_webhook_url_encrypted')
    op.alter_column('workspace_members', 'role',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'member'::character varying"),
                    existing_nullable=False)
    op.alter_column('profiles', 'is_onboarded',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    op.alter_column('digests', 'update_count',
                    existing_type=sa.INTEGER(),
                    server_default=sa.text('0'),
                    existing_nullable=False)
    op.alter_column('digests', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'pending'::character varying"),
                    existing_nullable=False)
    op.drop_column('digests', 'slack_delivered_at')
    op.drop_column('digests', 'delivered_to_slack')
    # ### end Alembic commands ###
