"""add_prompt_config_to_workspaces

Revision ID: 0c3ab14699e7
Revises: fdafb0962976
Create Date: 2026-05-19 22:03:07.306663+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3ab14699e7'  # pragma: allowlist secret
down_revision: Union[str, None] = 'fdafb0962976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('updates', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    existing_nullable=False)
    op.add_column('workspaces', sa.Column(
        'summarisation_prompt', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column(
        'digest_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'digest_prompt')
    op.drop_column('workspaces', 'summarisation_prompt')
    op.alter_column('updates', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text('false'),
                    existing_nullable=False)
    # ### end Alembic commands ###
