"""add_workspace_invites_table

Revision ID: c246201ec040
Revises: ece9056e024c
Create Date: 2026-06-03 22:08:10.641174+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c246201ec040'
down_revision: Union[str, None] = 'ece9056e024c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invites_code'), 'workspace_invites', ['code'], unique=True)
    op.create_index(op.f('ix_workspace_invites_email'), 'workspace_invites', ['email'], unique=False)
    op.create_index(op.f('ix_workspace_invites_workspace_id'), 'workspace_invites', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_invites_workspace_id'), table_name='workspace_invites')
    op.drop_index(op.f('ix_workspace_invites_email'), table_name='workspace_invites')
    op.drop_index(op.f('ix_workspace_invites_code'), table_name='workspace_invites')
    op.drop_table('workspace_invites')
    # ### end Alembic commands ###
